# https://taskfile.dev

version: '3'

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list
    silent: true

  dev:
    desc: Build and run development server
    cmds:
      - pnpm build
      - go run serve.go

  build:
    desc: Build demo components and styles
    cmds:
      - pnpm build
